<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>HoldKeyPlugin</AssemblyName>
    <OpenTabletDriverPath Condition="'$(OpenTabletDriverPath)' == ''">/Applications/OpenTabletDriver .app/Contents/MacOS</OpenTabletDriverPath>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="OpenTabletDriver">
      <HintPath>$(OpenTabletDriverPath)/OpenTabletDriver.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="OpenTabletDriver.Plugin">
      <HintPath>$(OpenTabletDriverPath)/OpenTabletDriver.Plugin.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
