namespace HoldKeyPlugin;

public static class MacKeyMap
{
    private static readonly Dictionary<string, ushort> KeyCodes = new(StringComparer.OrdinalIgnoreCase)
    {
        ["A"] = 0x00,
        ["S"] = 0x01,
        ["D"] = 0x02,
        ["F"] = 0x03,
        ["H"] = 0x04,
        ["G"] = 0x05,
        ["Z"] = 0x06,
        ["X"] = 0x07,
        ["C"] = 0x08,
        ["V"] = 0x09,
        ["B"] = 0x0B,
        ["Q"] = 0x0C,
        ["W"] = 0x0D,
        ["E"] = 0x0E,
        ["R"] = 0x0F,
        ["Y"] = 0x10,
        ["T"] = 0x11,
        ["D1"] = 0x12,
        ["D2"] = 0x13,
        ["D3"] = 0x14,
        ["D4"] = 0x15,
        ["D6"] = 0x16,
        ["D5"] = 0x17,
        ["Equal"] = 0x18,
        ["D9"] = 0x19,
        ["D7"] = 0x1A,
        ["Minus"] = 0x1B,
        ["D8"] = 0x1C,
        ["D0"] = 0x1D,
        ["RightBracket"] = 0x1E,
        ["O"] = 0x1F,
        ["U"] = 0x20,
        ["LeftBracket"] = 0x21,
        ["I"] = 0x22,
        ["P"] = 0x23,
        ["Enter"] = 0x24,
        ["L"] = 0x25,
        ["J"] = 0x26,
        ["Quote"] = 0x27,
        ["K"] = 0x28,
        ["Semicolon"] = 0x29,
        ["Backslash"] = 0x2A,
        ["Comma"] = 0x2B,
        ["Slash"] = 0x2C,
        ["N"] = 0x2D,
        ["M"] = 0x2E,
        ["Period"] = 0x2F,
        ["Tab"] = 0x30,
        ["Space"] = 0x31,
        ["Grave"] = 0x32,
        ["Backspace"] = 0x33,
        ["Escape"] = 0x35,
        ["Application"] = 0x37,
        ["Command"] = 0x37,
        ["Shift"] = 0x38,
        ["CapsLock"] = 0x39,
        ["Alt"] = 0x3A,
        ["Option"] = 0x3A,
        ["Control"] = 0x3B,
        ["RightShift"] = 0x3C,
        ["RightAlt"] = 0x3D,
        ["RightControl"] = 0x3E,
        ["RightApplication"] = 0x36,
        ["F1"] = 0x7A,
        ["F2"] = 0x78,
        ["F3"] = 0x63,
        ["F4"] = 0x76,
        ["F5"] = 0x60,
        ["F6"] = 0x61,
        ["F7"] = 0x62,
        ["F8"] = 0x64,
        ["F9"] = 0x65,
        ["F10"] = 0x6D,
        ["F11"] = 0x67,
        ["F12"] = 0x6F,
        ["Left"] = 0x7B,
        ["Right"] = 0x7C,
        ["Down"] = 0x7D,
        ["Up"] = 0x7E
    };

    private static readonly HashSet<string> Modifiers = new(StringComparer.OrdinalIgnoreCase)
    {
        "Application", "Command", "RightApplication",
        "Shift", "RightShift", "Alt", "Option", "RightAlt",
        "Control", "RightControl"
    };

    public static bool TryGetKeyCode(string key, out ushort keyCode) => KeyCodes.TryGetValue(key, out keyCode);
    public static bool IsModifier(string key) => Modifiers.Contains(key);
}
